name: Converter CI

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use the Node.js version of your choice

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run Jest tests
      - name: Run Jest tests
        run: npm test
